// Auto-generated list of countries with calling codes, ISO2 codes and flag emoji.
// Used by the phone sign-in country picker.
export interface Country {
  iso2: string;
  dial: string;
  name: string;
  nameAr: string;
  flag: string;
}

export const COUNTRIES: Country[] = [
  { iso2: 'AF', dial: '93', name: 'Afghanistan', nameAr: 'Afghanistan', flag: '🇦🇫' },
  { iso2: 'AL', dial: '355', name: 'Albania', nameAr: 'Albania', flag: '🇦🇱' },
  { iso2: 'DZ', dial: '213', name: 'Algeria', nameAr: 'الجزائر', flag: '🇩🇿' },
  { iso2: 'AD', dial: '376', name: 'Andorra', nameAr: 'Andorra', flag: '🇦🇩' },
  { iso2: 'AO', dial: '244', name: 'Angola', nameAr: 'Angola', flag: '🇦🇴' },
  { iso2: 'AR', dial: '54', name: 'Argentina', nameAr: 'Argentina', flag: '🇦🇷' },
  { iso2: 'AM', dial: '374', name: 'Armenia', nameAr: 'Armenia', flag: '🇦🇲' },
  { iso2: 'AU', dial: '61', name: 'Australia', nameAr: 'أستراليا', flag: '🇦🇺' },
  { iso2: 'AT', dial: '43', name: 'Austria', nameAr: 'Austria', flag: '🇦🇹' },
  { iso2: 'AZ', dial: '994', name: 'Azerbaijan', nameAr: 'Azerbaijan', flag: '🇦🇿' },
  { iso2: 'BH', dial: '973', name: 'Bahrain', nameAr: 'البحرين', flag: '🇧🇭' },
  { iso2: 'BD', dial: '880', name: 'Bangladesh', nameAr: 'Bangladesh', flag: '🇧🇩' },
  { iso2: 'BY', dial: '375', name: 'Belarus', nameAr: 'Belarus', flag: '🇧🇾' },
  { iso2: 'BE', dial: '32', name: 'Belgium', nameAr: 'Belgium', flag: '🇧🇪' },
  { iso2: 'BZ', dial: '501', name: 'Belize', nameAr: 'Belize', flag: '🇧🇿' },
  { iso2: 'BJ', dial: '229', name: 'Benin', nameAr: 'Benin', flag: '🇧🇯' },
  { iso2: 'BT', dial: '975', name: 'Bhutan', nameAr: 'Bhutan', flag: '🇧🇹' },
  { iso2: 'BO', dial: '591', name: 'Bolivia', nameAr: 'Bolivia', flag: '🇧🇴' },
  { iso2: 'BA', dial: '387', name: 'Bosnia and Herzegovina', nameAr: 'Bosnia and Herzegovina', flag: '🇧🇦' },
  { iso2: 'BW', dial: '267', name: 'Botswana', nameAr: 'Botswana', flag: '🇧🇼' },
  { iso2: 'BR', dial: '55', name: 'Brazil', nameAr: 'البرازيل', flag: '🇧🇷' },
  { iso2: 'BN', dial: '673', name: 'Brunei', nameAr: 'Brunei', flag: '🇧🇳' },
  { iso2: 'BG', dial: '359', name: 'Bulgaria', nameAr: 'Bulgaria', flag: '🇧🇬' },
  { iso2: 'BF', dial: '226', name: 'Burkina Faso', nameAr: 'Burkina Faso', flag: '🇧🇫' },
  { iso2: 'BI', dial: '257', name: 'Burundi', nameAr: 'Burundi', flag: '🇧🇮' },
  { iso2: 'KH', dial: '855', name: 'Cambodia', nameAr: 'Cambodia', flag: '🇰🇭' },
  { iso2: 'CM', dial: '237', name: 'Cameroon', nameAr: 'Cameroon', flag: '🇨🇲' },
  { iso2: 'CA', dial: '1', name: 'Canada', nameAr: 'كندا', flag: '🇨🇦' },
  { iso2: 'CV', dial: '238', name: 'Cape Verde', nameAr: 'Cape Verde', flag: '🇨🇻' },
  { iso2: 'CF', dial: '236', name: 'Central African Republic', nameAr: 'Central African Republic', flag: '🇨🇫' },
  { iso2: 'TD', dial: '235', name: 'Chad', nameAr: 'Chad', flag: '🇹🇩' },
  { iso2: 'CL', dial: '56', name: 'Chile', nameAr: 'Chile', flag: '🇨🇱' },
  { iso2: 'CN', dial: '86', name: 'China', nameAr: 'الصين', flag: '🇨🇳' },
  { iso2: 'CO', dial: '57', name: 'Colombia', nameAr: 'Colombia', flag: '🇨🇴' },
  { iso2: 'KM', dial: '269', name: 'Comoros', nameAr: 'جزر القمر', flag: '🇰🇲' },
  { iso2: 'CG', dial: '242', name: 'Congo', nameAr: 'Congo', flag: '🇨🇬' },
  { iso2: 'CR', dial: '506', name: 'Costa Rica', nameAr: 'Costa Rica', flag: '🇨🇷' },
  { iso2: 'HR', dial: '385', name: 'Croatia', nameAr: 'Croatia', flag: '🇭🇷' },
  { iso2: 'CU', dial: '53', name: 'Cuba', nameAr: 'Cuba', flag: '🇨🇺' },
  { iso2: 'CY', dial: '357', name: 'Cyprus', nameAr: 'Cyprus', flag: '🇨🇾' },
  { iso2: 'CZ', dial: '420', name: 'Czech Republic', nameAr: 'Czech Republic', flag: '🇨🇿' },
  { iso2: 'CD', dial: '243', name: 'DR Congo', nameAr: 'DR Congo', flag: '🇨🇩' },
  { iso2: 'DK', dial: '45', name: 'Denmark', nameAr: 'Denmark', flag: '🇩🇰' },
  { iso2: 'DJ', dial: '253', name: 'Djibouti', nameAr: 'جيبوتي', flag: '🇩🇯' },
  { iso2: 'DO', dial: '1', name: 'Dominican Republic', nameAr: 'Dominican Republic', flag: '🇩🇴' },
  { iso2: 'EC', dial: '593', name: 'Ecuador', nameAr: 'Ecuador', flag: '🇪🇨' },
  { iso2: 'EG', dial: '20', name: 'Egypt', nameAr: 'مصر', flag: '🇪🇬' },
  { iso2: 'SV', dial: '503', name: 'El Salvador', nameAr: 'El Salvador', flag: '🇸🇻' },
  { iso2: 'EE', dial: '372', name: 'Estonia', nameAr: 'Estonia', flag: '🇪🇪' },
  { iso2: 'ET', dial: '251', name: 'Ethiopia', nameAr: 'Ethiopia', flag: '🇪🇹' },
  { iso2: 'FJ', dial: '679', name: 'Fiji', nameAr: 'Fiji', flag: '🇫🇯' },
  { iso2: 'FI', dial: '358', name: 'Finland', nameAr: 'Finland', flag: '🇫🇮' },
  { iso2: 'FR', dial: '33', name: 'France', nameAr: 'فرنسا', flag: '🇫🇷' },
  { iso2: 'GA', dial: '241', name: 'Gabon', nameAr: 'Gabon', flag: '🇬🇦' },
  { iso2: 'GM', dial: '220', name: 'Gambia', nameAr: 'Gambia', flag: '🇬🇲' },
  { iso2: 'GE', dial: '995', name: 'Georgia', nameAr: 'Georgia', flag: '🇬🇪' },
  { iso2: 'DE', dial: '49', name: 'Germany', nameAr: 'ألمانيا', flag: '🇩🇪' },
  { iso2: 'GH', dial: '233', name: 'Ghana', nameAr: 'Ghana', flag: '🇬🇭' },
  { iso2: 'GR', dial: '30', name: 'Greece', nameAr: 'Greece', flag: '🇬🇷' },
  { iso2: 'GT', dial: '502', name: 'Guatemala', nameAr: 'Guatemala', flag: '🇬🇹' },
  { iso2: 'GN', dial: '224', name: 'Guinea', nameAr: 'Guinea', flag: '🇬🇳' },
  { iso2: 'HT', dial: '509', name: 'Haiti', nameAr: 'Haiti', flag: '🇭🇹' },
  { iso2: 'HN', dial: '504', name: 'Honduras', nameAr: 'Honduras', flag: '🇭🇳' },
  { iso2: 'HK', dial: '852', name: 'Hong Kong', nameAr: 'Hong Kong', flag: '🇭🇰' },
  { iso2: 'HU', dial: '36', name: 'Hungary', nameAr: 'Hungary', flag: '🇭🇺' },
  { iso2: 'IS', dial: '354', name: 'Iceland', nameAr: 'Iceland', flag: '🇮🇸' },
  { iso2: 'IN', dial: '91', name: 'India', nameAr: 'الهند', flag: '🇮🇳' },
  { iso2: 'ID', dial: '62', name: 'Indonesia', nameAr: 'Indonesia', flag: '🇮🇩' },
  { iso2: 'IR', dial: '98', name: 'Iran', nameAr: 'إيران', flag: '🇮🇷' },
  { iso2: 'IQ', dial: '964', name: 'Iraq', nameAr: 'العراق', flag: '🇮🇶' },
  { iso2: 'IE', dial: '353', name: 'Ireland', nameAr: 'Ireland', flag: '🇮🇪' },
  { iso2: 'IL', dial: '972', name: 'Israel', nameAr: 'Israel', flag: '🇮🇱' },
  { iso2: 'IT', dial: '39', name: 'Italy', nameAr: 'إيطاليا', flag: '🇮🇹' },
  { iso2: 'CI', dial: '225', name: 'Ivory Coast', nameAr: 'Ivory Coast', flag: '🇨🇮' },
  { iso2: 'JM', dial: '1', name: 'Jamaica', nameAr: 'Jamaica', flag: '🇯🇲' },
  { iso2: 'JP', dial: '81', name: 'Japan', nameAr: 'Japan', flag: '🇯🇵' },
  { iso2: 'JO', dial: '962', name: 'Jordan', nameAr: 'الأردن', flag: '🇯🇴' },
  { iso2: 'KZ', dial: '7', name: 'Kazakhstan', nameAr: 'Kazakhstan', flag: '🇰🇿' },
  { iso2: 'KE', dial: '254', name: 'Kenya', nameAr: 'Kenya', flag: '🇰🇪' },
  { iso2: 'KW', dial: '965', name: 'Kuwait', nameAr: 'الكويت', flag: '🇰🇼' },
  { iso2: 'KG', dial: '996', name: 'Kyrgyzstan', nameAr: 'Kyrgyzstan', flag: '🇰🇬' },
  { iso2: 'LA', dial: '856', name: 'Laos', nameAr: 'Laos', flag: '🇱🇦' },
  { iso2: 'LV', dial: '371', name: 'Latvia', nameAr: 'Latvia', flag: '🇱🇻' },
  { iso2: 'LB', dial: '961', name: 'Lebanon', nameAr: 'لبنان', flag: '🇱🇧' },
  { iso2: 'LS', dial: '266', name: 'Lesotho', nameAr: 'Lesotho', flag: '🇱🇸' },
  { iso2: 'LR', dial: '231', name: 'Liberia', nameAr: 'Liberia', flag: '🇱🇷' },
  { iso2: 'LY', dial: '218', name: 'Libya', nameAr: 'ليبيا', flag: '🇱🇾' },
  { iso2: 'LI', dial: '423', name: 'Liechtenstein', nameAr: 'Liechtenstein', flag: '🇱🇮' },
  { iso2: 'LT', dial: '370', name: 'Lithuania', nameAr: 'Lithuania', flag: '🇱🇹' },
  { iso2: 'LU', dial: '352', name: 'Luxembourg', nameAr: 'Luxembourg', flag: '🇱🇺' },
  { iso2: 'MO', dial: '853', name: 'Macau', nameAr: 'Macau', flag: '🇲🇴' },
  { iso2: 'MK', dial: '389', name: 'Macedonia', nameAr: 'Macedonia', flag: '🇲🇰' },
  { iso2: 'MG', dial: '261', name: 'Madagascar', nameAr: 'Madagascar', flag: '🇲🇬' },
  { iso2: 'MW', dial: '265', name: 'Malawi', nameAr: 'Malawi', flag: '🇲🇼' },
  { iso2: 'MY', dial: '60', name: 'Malaysia', nameAr: 'Malaysia', flag: '🇲🇾' },
  { iso2: 'MV', dial: '960', name: 'Maldives', nameAr: 'Maldives', flag: '🇲🇻' },
  { iso2: 'ML', dial: '223', name: 'Mali', nameAr: 'Mali', flag: '🇲🇱' },
  { iso2: 'MT', dial: '356', name: 'Malta', nameAr: 'Malta', flag: '🇲🇹' },
  { iso2: 'MR', dial: '222', name: 'Mauritania', nameAr: 'موريتانيا', flag: '🇲🇷' },
  { iso2: 'MU', dial: '230', name: 'Mauritius', nameAr: 'Mauritius', flag: '🇲🇺' },
  { iso2: 'MX', dial: '52', name: 'Mexico', nameAr: 'Mexico', flag: '🇲🇽' },
  { iso2: 'MD', dial: '373', name: 'Moldova', nameAr: 'Moldova', flag: '🇲🇩' },
  { iso2: 'MC', dial: '377', name: 'Monaco', nameAr: 'Monaco', flag: '🇲🇨' },
  { iso2: 'MN', dial: '976', name: 'Mongolia', nameAr: 'Mongolia', flag: '🇲🇳' },
  { iso2: 'ME', dial: '382', name: 'Montenegro', nameAr: 'Montenegro', flag: '🇲🇪' },
  { iso2: 'MA', dial: '212', name: 'Morocco', nameAr: 'المغرب', flag: '🇲🇦' },
  { iso2: 'MZ', dial: '258', name: 'Mozambique', nameAr: 'Mozambique', flag: '🇲🇿' },
  { iso2: 'MM', dial: '95', name: 'Myanmar', nameAr: 'Myanmar', flag: '🇲🇲' },
  { iso2: 'NA', dial: '264', name: 'Namibia', nameAr: 'Namibia', flag: '🇳🇦' },
  { iso2: 'NP', dial: '977', name: 'Nepal', nameAr: 'Nepal', flag: '🇳🇵' },
  { iso2: 'NL', dial: '31', name: 'Netherlands', nameAr: 'هولندا', flag: '🇳🇱' },
  { iso2: 'NZ', dial: '64', name: 'New Zealand', nameAr: 'New Zealand', flag: '🇳🇿' },
  { iso2: 'NI', dial: '505', name: 'Nicaragua', nameAr: 'Nicaragua', flag: '🇳🇮' },
  { iso2: 'NE', dial: '227', name: 'Niger', nameAr: 'Niger', flag: '🇳🇪' },
  { iso2: 'NG', dial: '234', name: 'Nigeria', nameAr: 'Nigeria', flag: '🇳🇬' },
  { iso2: 'NO', dial: '47', name: 'Norway', nameAr: 'Norway', flag: '🇳🇴' },
  { iso2: 'OM', dial: '968', name: 'Oman', nameAr: 'عُمان', flag: '🇴🇲' },
  { iso2: 'PK', dial: '92', name: 'Pakistan', nameAr: 'باكستان', flag: '🇵🇰' },
  { iso2: 'PS', dial: '970', name: 'Palestine', nameAr: 'فلسطين', flag: '🇵🇸' },
  { iso2: 'PA', dial: '507', name: 'Panama', nameAr: 'Panama', flag: '🇵🇦' },
  { iso2: 'PG', dial: '675', name: 'Papua New Guinea', nameAr: 'Papua New Guinea', flag: '🇵🇬' },
  { iso2: 'PY', dial: '595', name: 'Paraguay', nameAr: 'Paraguay', flag: '🇵🇾' },
  { iso2: 'PE', dial: '51', name: 'Peru', nameAr: 'Peru', flag: '🇵🇪' },
  { iso2: 'PH', dial: '63', name: 'Philippines', nameAr: 'Philippines', flag: '🇵🇭' },
  { iso2: 'PL', dial: '48', name: 'Poland', nameAr: 'Poland', flag: '🇵🇱' },
  { iso2: 'PT', dial: '351', name: 'Portugal', nameAr: 'Portugal', flag: '🇵🇹' },
  { iso2: 'QA', dial: '974', name: 'Qatar', nameAr: 'قطر', flag: '🇶🇦' },
  { iso2: 'RO', dial: '40', name: 'Romania', nameAr: 'Romania', flag: '🇷🇴' },
  { iso2: 'RU', dial: '7', name: 'Russia', nameAr: 'روسيا', flag: '🇷🇺' },
  { iso2: 'RW', dial: '250', name: 'Rwanda', nameAr: 'Rwanda', flag: '🇷🇼' },
  { iso2: 'SA', dial: '966', name: 'Saudi Arabia', nameAr: 'السعودية', flag: '🇸🇦' },
  { iso2: 'SN', dial: '221', name: 'Senegal', nameAr: 'Senegal', flag: '🇸🇳' },
  { iso2: 'RS', dial: '381', name: 'Serbia', nameAr: 'Serbia', flag: '🇷🇸' },
  { iso2: 'SC', dial: '248', name: 'Seychelles', nameAr: 'Seychelles', flag: '🇸🇨' },
  { iso2: 'SL', dial: '232', name: 'Sierra Leone', nameAr: 'Sierra Leone', flag: '🇸🇱' },
  { iso2: 'SG', dial: '65', name: 'Singapore', nameAr: 'Singapore', flag: '🇸🇬' },
  { iso2: 'SK', dial: '421', name: 'Slovakia', nameAr: 'Slovakia', flag: '🇸🇰' },
  { iso2: 'SI', dial: '386', name: 'Slovenia', nameAr: 'Slovenia', flag: '🇸🇮' },
  { iso2: 'SO', dial: '252', name: 'Somalia', nameAr: 'الصومال', flag: '🇸🇴' },
  { iso2: 'ZA', dial: '27', name: 'South Africa', nameAr: 'South Africa', flag: '🇿🇦' },
  { iso2: 'KR', dial: '82', name: 'South Korea', nameAr: 'South Korea', flag: '🇰🇷' },
  { iso2: 'SS', dial: '211', name: 'South Sudan', nameAr: 'South Sudan', flag: '🇸🇸' },
  { iso2: 'ES', dial: '34', name: 'Spain', nameAr: 'إسبانيا', flag: '🇪🇸' },
  { iso2: 'LK', dial: '94', name: 'Sri Lanka', nameAr: 'Sri Lanka', flag: '🇱🇰' },
  { iso2: 'SD', dial: '249', name: 'Sudan', nameAr: 'السودان', flag: '🇸🇩' },
  { iso2: 'SR', dial: '597', name: 'Suriname', nameAr: 'Suriname', flag: '🇸🇷' },
  { iso2: 'SE', dial: '46', name: 'Sweden', nameAr: 'السويد', flag: '🇸🇪' },
  { iso2: 'CH', dial: '41', name: 'Switzerland', nameAr: 'Switzerland', flag: '🇨🇭' },
  { iso2: 'SY', dial: '963', name: 'Syria', nameAr: 'سوريا', flag: '🇸🇾' },
  { iso2: 'TW', dial: '886', name: 'Taiwan', nameAr: 'Taiwan', flag: '🇹🇼' },
  { iso2: 'TJ', dial: '992', name: 'Tajikistan', nameAr: 'Tajikistan', flag: '🇹🇯' },
  { iso2: 'TZ', dial: '255', name: 'Tanzania', nameAr: 'Tanzania', flag: '🇹🇿' },
  { iso2: 'TH', dial: '66', name: 'Thailand', nameAr: 'Thailand', flag: '🇹🇭' },
  { iso2: 'TG', dial: '228', name: 'Togo', nameAr: 'Togo', flag: '🇹🇬' },
  { iso2: 'TN', dial: '216', name: 'Tunisia', nameAr: 'تونس', flag: '🇹🇳' },
  { iso2: 'TR', dial: '90', name: 'Turkey', nameAr: 'تركيا', flag: '🇹🇷' },
  { iso2: 'TM', dial: '993', name: 'Turkmenistan', nameAr: 'Turkmenistan', flag: '🇹🇲' },
  { iso2: 'UG', dial: '256', name: 'Uganda', nameAr: 'Uganda', flag: '🇺🇬' },
  { iso2: 'UA', dial: '380', name: 'Ukraine', nameAr: 'Ukraine', flag: '🇺🇦' },
  { iso2: 'AE', dial: '971', name: 'United Arab Emirates', nameAr: 'الإمارات', flag: '🇦🇪' },
  { iso2: 'GB', dial: '44', name: 'United Kingdom', nameAr: 'المملكة المتحدة', flag: '🇬🇧' },
  { iso2: 'US', dial: '1', name: 'United States', nameAr: 'الولايات المتحدة', flag: '🇺🇸' },
  { iso2: 'UY', dial: '598', name: 'Uruguay', nameAr: 'Uruguay', flag: '🇺🇾' },
  { iso2: 'UZ', dial: '998', name: 'Uzbekistan', nameAr: 'Uzbekistan', flag: '🇺🇿' },
  { iso2: 'VE', dial: '58', name: 'Venezuela', nameAr: 'Venezuela', flag: '🇻🇪' },
  { iso2: 'VN', dial: '84', name: 'Vietnam', nameAr: 'Vietnam', flag: '🇻🇳' },
  { iso2: 'YE', dial: '967', name: 'Yemen', nameAr: 'اليمن', flag: '🇾🇪' },
  { iso2: 'ZM', dial: '260', name: 'Zambia', nameAr: 'Zambia', flag: '🇿🇲' },
  { iso2: 'ZW', dial: '263', name: 'Zimbabwe', nameAr: 'Zimbabwe', flag: '🇿🇼' },
];
